# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('CantidadExistente', models.PositiveIntegerField(default=0)),
                ('CantidadPorHectarea', models.PositiveIntegerField(default=0)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
