# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_semilla_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semilla',
            name='Telefono',
            field=models.IntegerField(default=9341051950),
        ),
    ]
