# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20171014_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semilla',
            name='Cantidad',
        ),
        migrations.RemoveField(
            model_name='semilla',
            name='Telefono',
        ),
        migrations.AlterField(
            model_name='semilla',
            name='CantidadExistente',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad existente en KG'),
        ),
        migrations.AlterField(
            model_name='semilla',
            name='CantidadPorHectarea',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad en KG que se movimiento por Hectárea'),
        ),
    ]
