# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ApMaterno',
            field=models.CharField(max_length=50, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ApPaterno',
            field=models.CharField(max_length=50, verbose_name='Apellido paterno'),
        ),
    ]
