# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaAgricultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEntrega', models.DateField(auto_now=True, verbose_name='Fecha de movimiento')),
                ('HectareasAPlantar', models.PositiveIntegerField(verbose_name='Hectareas a plantar')),
                ('SemillasDadas', models.PositiveIntegerField(default=1, editable=False, verbose_name='KG de semillas dadas')),
            ],
        ),
    ]
