# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20171014_1936'),
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaagricultor',
            name='TipoSemilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.Semilla'),
        ),
        migrations.AlterField(
            model_name='entregaagricultor',
            name='SemillasDadas',
            field=models.PositiveIntegerField(default=1, verbose_name='KG de semillas dadas'),
        ),
    ]
