# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20171014_2134'),
        ('movimiento', '0002_auto_20171014_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaagricultor',
            name='NombreAgricultor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuario.Agricultor'),
        ),
    ]
