# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20171014_2134'),
        ('inventario', '0004_auto_20171014_1936'),
        ('movimiento', '0003_entregaagricultor_nombreagricultor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaAAgricultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaEntrega', models.DateField(auto_now=True, verbose_name='Fecha de movimiento')),
                ('HectareasAPlantar', models.PositiveIntegerField(verbose_name='Hectareas a plantar')),
                ('SemillasDadas', models.PositiveIntegerField(default=1, verbose_name='KG de semillas dadas')),
                ('NombreAgricultor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuario.Agricultor', verbose_name='Agricultor al que se le darán las semillas')),
                ('TipoSemilla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.Semilla', verbose_name='Tipo de semillas que se darán')),
            ],
        ),
        migrations.RemoveField(
            model_name='entregaagricultor',
            name='NombreAgricultor',
        ),
        migrations.RemoveField(
            model_name='entregaagricultor',
            name='TipoSemilla',
        ),
        migrations.DeleteModel(
            name='EntregaAgricultor',
        ),
    ]
